### ISSUE TITLE
Mouse control for translation improvements

### ISSUE THREAD

**Issue by kephale** [scenerygraphics/sciview#118]
We should try to maintain a 1-to-1 correspondence with the mouse's translation and the point on the object/scene that the user clicked on. This is more intuitive for the Node translation mechanism, but the camera translation should probably be similar-ish to how it works now.

**Comment by skalarproduktraum** [comment]
Can you elaborate? I'm not sure I understand the first sentence :-/

**Comment by kephale** [comment]
There are some more general issues about making sure that the controls match the typical behavior of 3D editing programs. Such as rotation axes based upon where the user clicked.

**Comment by skalarproduktraum** [comment]
Done and improved with Vlado's recent PRs.
