### ISSUE TITLE
Keeping images in cache

### ISSUE THREAD

**Issue by DaetwylerStephan** [scenerygraphics/sciview#134]
Sciview seems to keep images in cache. After closing an image and modifying it outside of sciview, sciview does not open the modified version but reopens the old one. Keeping the images too long in buffer, can also lead to full buffers and preventing the opening of new files when the allocated memory is used up.

**Comment by kephale** [comment]
I'm closing this because almost all of the code that would affect this issue has changed since the original issue was posted. I also believe we would have heard about this issue again.
