### ISSUE TITLE
Volumes do not display from update site version of SciView, but do display from IntelliJ builds (OS X only?)

### ISSUE THREAD

**Issue by kephale** [scenerygraphics/sciview#139]
On OS X:

1. Open Fiji
2. Run SciView
3. Demo>Volume Render
4. Edit>Toggle floor & View>Center on active node
5. View>Toggle bounding grid to confirm that SciView thinks the volume is there and has the right size.

This does not happen on Ubuntu, but I and others have confirmed this using SciView from the update site on OS X.

**Comment by skalarproduktraum** [comment]
This could be related to the race condition when adding volumes that I have fixed yesterday. Will verify...

**Comment by skalarproduktraum** [comment]
Fixed with #141.
