### ISSUE TITLE
Add a command/menu entry to toggle VR mode

### ISSUE THREAD

**Issue by kephale** [scenerygraphics/sciview#143]
Yes, there is a keybind for this already, but having a menu entry will make it easier for people to notice/realize that there is VR support.

**Comment by skalarproduktraum** [comment]
I'll take care of this, as it might also require renderer reinit and so on...

**Comment by kephale** [comment]
@skalarproduktraum bump, im guessing this is an easy one for you

**Comment by skalarproduktraum** [comment]
How about https://github.com/scenerygraphics/sciview/blob/master/src/main/java/sc/iview/commands/view/RenderToOpenVRHMD.java 👍

**Comment by skalarproduktraum** [comment]
I'll close this, probably just was missed the last time.
