### ISSUE TITLE
Add @Parameter for Mesh's

### ISSUE THREAD

**Issue by kephale** [scenerygraphics/sciview#150]

**Comment by kephale** [comment]
@ctrueden questions about this (no rush):

1. Do we want the widget to be a dropdown menu of all meshes available in the currently active SciView window?
2. Would there be any obvious issues with coding this as something like `MeshWidget` that implements `InputWidget` which has an `@Parameter` for a `SciView`?
3. What is the best existing code snippet to reference for implementation?

**Comment by imagejan** [comment]
How about registering `Mesh`es with the `ObjectService` when they're created/displayed? Then a `ChoiceWidget` would be created automatically (taking the `toString()` as a name, IIRC).

To also allow `#@ Mesh` in scripting, all you need is add an alias from `Mesh` to `net.imagej.mesh.Mesh` using `ScriptService.addAlias()`

**Comment by kephale** [comment]
!
That sounds smart. We'll check it out.

**Comment by kephale** [comment]
Thank you kindly @imagejan 

Addressed in https://github.com/scenerygraphics/sciview/commit/90e2d5212278e897d943bcc7d3863278a661c46d

**Comment by ctrueden** [comment]
Awesome, @kephale!

The only thing to watch out for is: `ObjectService`'s index keeps hard refs, so your meshes will not be GCed unless you remove them explicitly. Maybe do that when they are removed from all scenes? You'll probably have to reference count, unfortunately.

Alternately, we could look at adding weak reference support to the object service. Let me know if that would help you.

**Comment by kephale** [comment]
This one is flagged for https://github.com/scenerygraphics/sciview/issues?q=is%3Aopen+label%3A1.0.0+sort%3Aupdated-desc to check the situation w.r.t. @ctrueden's comment

**Comment by kephale** [comment]
Node deletion also removes them from the ObjectService now. 

I did notice that `SciView.dispose()` does not use `deleteNode`. That is important because there may be some memory reference issues with scenery's volume manager that @moreApi mentioned in another issue, and `deleteNode` also handles special case cleanup for `Volume`s, including removal from `VolumeManager`. This would be addressed by https://github.com/scenerygraphics/sciview/pull/478
