### ISSUE TITLE
SciView on forum.image.sc toolbar

### ISSUE THREAD

**Issue by kephale** [scenerygraphics/sciview#155]
Before the final release, just for @tpietzsch <3

**Comment by ctrueden** [comment]
Is there a logo? Once there is a logo, we can add it any time. 😄

**Comment by kephale** [comment]
There is (any good project timeline goes: name, logo, then write code, right?)
https://github.com/scenerygraphics/artwork

**Comment by ctrueden** [comment]
Oh, right! Do you want me to add it to the partners now?

**Comment by kephale** [comment]
Yes please!!

**Comment by ctrueden** [comment]
I added both Scenery and SciView, with the same icon, and adapted blurbs from their online presence. Let me know if it needs correction.
