### ISSUE TITLE
GoL demo volume rending off

### ISSUE THREAD

**Issue by kephale** [scenerygraphics/sciview#156]
It looks like the edges of voxels are being rendered but not their interior?

![image](https://user-images.githubusercontent.com/400105/53212806-6c8df800-3614-11e9-8e5d-d9bb469249c1.png)

**Comment by skalarproduktraum** [comment]
I think this is an issue with how the volume shader handles data that is only binary, which probably causes some interpolation to produce strange-looking results, as seen aboven. I will have a look into this.

**Comment by skalarproduktraum** [comment]
This is already fixed in 0.2.0-beta-1.
