### ISSUE TITLE
Enable fast camera movement with certain key combination

### ISSUE THREAD

**Issue by aryaman-gupta** [scenerygraphics/sciview#157]
E.g. Holding Ctrl + Shift along with camera movement keys (W, A, S, D). This would make navigation around large objects easier.

**Comment by kephale** [comment]
Addressed in part by https://github.com/scenerygraphics/sciview/commit/b93a8cc43461db07993064ef6555db52e0e3dab5

Related to https://github.com/scenerygraphics/scenery/issues/242
