### ISSUE TITLE
Center camera on a node by double clicking on it in the Node Properties window

### ISSUE THREAD

**Issue by aryaman-gupta** [scenerygraphics/sciview#162]
I know the center on active node option is there in the menu, but I think quicker access to this functionality by double-clicking on a node would be helpful.

**Comment by skalarproduktraum** [comment]
This should actually work exactly like that, have you tried?

**Comment by aryaman-gupta** [comment]
Yes, I have, and it isn't working like that. Double-clicking on a node activates the node, but doesn't center the camera on the node.

**Comment by skalarproduktraum** [comment]
Ah, sorry, I had misunderstood. What does @kephale think about centering-on-double-click?

**Comment by kephale** [comment]
That is a great idea

**Comment by skalarproduktraum** [comment]
Fixed in #186.
