### ISSUE TITLE
BDV and SciView clash in Fiji

### ISSUE THREAD

**Issue by kephale** [scenerygraphics/sciview#173]
https://forum.image.sc/t/blank-image-window-bigdataviewer-bigsticher-multiview-reconstruction/22840/2

**Comment by skalarproduktraum** [comment]
Our update site includes a version of imglib2 that should not be there at all, see https://sites.imagej.net/SciView/jars/?C=M;O=D

Maybe we should clean out the update site?

**Comment by kephale** [comment]
Aha, can do tomorrow. Could we sneak out a release to go with that fix?

**Comment by skalarproduktraum** [comment]
Yes, I am fixing things still atm, and probably be ready for a release tomorrow 👍

**Comment by imagejan** [comment]
For the record, here's the list of files currently *overriding* a version shipped from the ImageJ/Java-8 update sites.

![image](https://user-images.githubusercontent.com/2033938/55078577-c1e97900-509a-11e9-9e55-ba4b761051c1.png)

I think except for `ImageJ-win64.exe`, they were not meant to be overridden, but were defined in a `pom-scijava` version more recent than the one currently used by `fiji/fiji`, and hence picked up by automatic tooling, right?

**Comment by skalarproduktraum** [comment]
The ones meant to be overridden are:

* imagej-launcher (because sciview uses the version to determine whether the XInitThreads fix is included or not)
* ffmpeg
* kryo
* javacpp

**Comment by skalarproduktraum** [comment]
Minlog, objenesis and batch-processor should not be there, though.
