### ISSUE TITLE
Duplicate dependencies shipping via update site

### ISSUE THREAD

**Issue by haesleinhuepf** [scenerygraphics/sciview#179]
Hey guys, 

congrats to the new beta release. I was just updating my Fiji while I saw that it ships with several versions of CoreMem. I'm afraid this might cause issues with ClearVolume and CLIJ. 

![image](https://user-images.githubusercontent.com/12660498/54871987-65960900-4dbd-11e9-9a24-ebf51f96a291.png)

Can we maybe decide on which version of CoreMem to use and ship it together with Fiji?

Cheers,
Robert

**Comment by imagejan** [comment]
`pom-scijava` [manages](https://github.com/scijava/pom-scijava/blob/b984777dd18a73e912ee9cf50b240eafc79152fb/pom.xml#L616-L617) `net.coremem.CoreMem` at version `0.4.3`. Since then, the capitalization of the artifactId (`net.coremem:coremem:0.4.5`) and the `groupId` (`net.clearcontrol:coremem:0.4.6`) have been changed. (BTW, none of `coremem.net` or `clearcontrol.net` seems to be valid, registered domains, which would be good practice for groupId naming.)

@skalarproduktraum, @kephale, @haesleinhuepf maybe someone of you can submit a PR to `pom-scijava` to correct things there? AFAICT, only scenery, SciView, ClearVolume and CLIJ depend on this component.

**Comment by skalarproduktraum** [comment]
@imagejan, thanks for the insight! That particular dependency was driving me nuts yesterday. I will submit a PR to pom-scijava. 

Regarding the domains: I thought @royerloic had at least registered clearvolume.net?

**Comment by skalarproduktraum** [comment]
@haesleinhuepf I guess then `net.clearcontrol:coremem:0.4.6.` would be the correct one?

**Comment by haesleinhuepf** [comment]
Apparently, 0.4.7 is the recent version of coremem. Maybe @royerloic can confirm?

https://github.com/ClearControl/master/blob/master/master.gradle#L14

**Comment by imagejan** [comment]
`0.4.7` doesn't seem to be deployed to maven (yet):
http://maven.imagej.net/#nexus-search;quick~coremem

**Comment by haesleinhuepf** [comment]
Alright, then let's go with 0.4.6... Btw. CLIJ uses a fork of coremem in order to prevent ClearVolume from breaking, if CLIJ and ClearVolume are installed at the same time. Reason is that ClearVolume ships with 0.3.2... See
https://sites.imagej.net/ClearVolume/jars/
and 
https://github.com/clij/clij/issues/15

Just mentioning, if this happens with Scenery as well, I'm happy tell more details on the workaround I implemented.

**Comment by imagejan** [comment]
> I'm happy tell more details on the workaround I implemented.

It seems you manually shaded `coremem` and `clearcl` for CLIJ. Is this something that could be solved by the [Maven Shade Plugin](https://maven.apache.org/plugins/maven-shade-plugin/)?

**Comment by skalarproduktraum** [comment]
@haesleinhuepf I just checked the ClearVolume code, what I found was it's using the latest ClearCL and thereby also coremem 0.4.6. Could it be that just imglib2-clearvolume hasn't been updated to reflect that?

**Comment by haesleinhuepf** [comment]
Indeed. I think the last update to the update site and respective repository was some time ago...
https://github.com/ClearVolume/imglib2-clearvolume/blame/a77d7dd8d26ca28a06708e509d7597173c8f9864/pom.xml#L103

**Comment by skalarproduktraum** [comment]
Okay, updated all the dependencies in imglib2-clearvolume. ClearVolume itself was already in a good shape :+1: Now the problem is that I do not have the login for the update site -- maybe @royerloic or @fjug can help here?

**Comment by haesleinhuepf** [comment]
Thanks for updating! I tried the recent code on the master branch and found an issue...
https://github.com/ClearVolume/imglib2-clearvolume/issues/16

**Comment by royerloic** [comment]
Hi all,
I think the real fix should be to finally update ClearVolume to the latest versions...
That would probably take care of most of the issues mentioned here.

**Comment by royerloic** [comment]
Ok, I have just sent an email to @skalarproduktraum with the necessary info for updating the update site. Thanks guys for your help! @skalarproduktraum : Feel free to advertise a new version of ClearVolume on Twitter. I think the latest version addresses a few issues and has better stability. We never got around with pushing it to the update site...

**Comment by skalarproduktraum** [comment]
Thanks, @royerloic! In the meantime I was told that you can just have your account added to the ACL of an update site, so I am now personally allowed to push to the CV update site :) Thanks for the email anyway!

**Comment by kephale** [comment]
@skalarproduktraum This can be closed i think?

**Comment by kephale** [comment]
This has been addressed.
