### ISSUE TITLE
Scroll bars don't appear in node property editor

### ISSUE THREAD

**Issue by skalarproduktraum** [scenerygraphics/sciview#181]
When activating a node in the tree view, the property editor loads the respective pane, but the scroll bars might fail to appear as in:
![Screenshot from 2019-03-26 15-27-08](https://user-images.githubusercontent.com/586495/55005084-ad927700-4fdb-11e9-9c6c-4b543187bf9e.png)

## Expected Behaviour 
Overflowing panel should be scrollable.

## Actual Behaviour
Scrollbars do not appear.

## Workaround
Resize any of the panels after selecting the node.

**Comment by skalarproduktraum** [comment]
Maybe @ctrueden has an idea why this occurs?

**Comment by skalarproduktraum** [comment]
Found, there's a `setSize()` needed on the JPanel, with the size of the newly incoming component.

**Comment by ctrueden** [comment]
@skalarproduktraum Usually you don't call `setSize()` on anything, but instead call `setPreferredSize()` and/or `setMinimumSize()` and sometimes `setMaximumSize()`. And then `pack()` then window. Or `validate()` + `repaint()`. But if `setSize()` is working here, then it's probably fine to not about it worry too much. Can always improve the behavior later if it causes issues for anyone.
