### ISSUE TITLE
Add config/parameter/commands for...

### ISSUE THREAD

**Issue by kephale** [scenerygraphics/sciview#191]
- scenery.Renderer.SupersamplingFactor
- Cutoff distance

**Comment by skalarproduktraum** [comment]
With cutoff distance you mean the far plane?

**Comment by kephale** [comment]
Yes

**Comment by kephale** [comment]
Cutoff command request is a duplicate of https://github.com/scenerygraphics/sciview/issues/51

**Comment by kephale** [comment]
@skalarproduktraum I am unsure why this does not seem to adjust the farplane: https://github.com/scenerygraphics/sciview/blob/e95c3c5207f2779af9b95c52f021e13d9e4fdda7/src/main/java/sc/iview/commands/view/SetFarPlane.java

If I set it to something like 10 and move away from a mesh the mesh does not disappear.
