### ISSUE TITLE
LogLevel not followed

### ISSUE THREAD

**Issue by kephale** [scenerygraphics/sciview#221]
I made this commit https://github.com/scenerygraphics/sciview/commit/e67a0a3cfbe49eb5815ee0c9f927d1c92a3a2703
because logService.info() continued to be emitted after setting log level to be greater than LogLevel.INFO after trying to set the log level in many places

**Comment by skalarproduktraum** [comment]
Could that be related to https://github.com/scenerygraphics/sciview/blob/7d603b3d69574bad2db132f07b6262ae24394659/src/main/java/sc/iview/Main.java#L52 ?

**Comment by kephale** [comment]
If that line was the cause, then it would prevent info from being emitted since it is a lower log level than debug?

**Comment by kephale** [comment]
I don't think this is relevant anymore.
