### ISSUE TITLE
Bounding box labels

### ISSUE THREAD

**Issue by kephale** [scenerygraphics/sciview#231]
This issue should probably go upstream to scenery.

When i generate a video with a bounding box, I would like to have more control over the labels. More importantly, the default labels should be closer to what is actually desired. There aren't numbers/units displayed as is, so the labels actually have to be replaced post-video recording.

**Comment by skalarproduktraum** [comment]
The labels are just normal members of the scene graph, so you can manipulate them at your leisure. If an object has a bounding box, that bounding box will be one of the children. The bounding box in turn has the labels as children, and you can modify the `label.text` property to your liking.

**Comment by kephale** [comment]
Oh gee, it is almost like some thoughtful developer planned for these things...

**Comment by kephale** [comment]
This begs for a demo but should be resolved.
