### ISSUE TITLE
Apply commands to children of Node's

### ISSUE THREAD

**Issue by kephale** [scenerygraphics/sciview#241]
Add support for applying a command to all children of a Node, e.g. apply LUT to a `Group` node which contains many spheres

**Comment by kephale** [comment]
It would be cool if this could take a lambda with a signature of (Node) -> (Vector4)

**Comment by skalarproduktraum** [comment]
There is Node.runRecursive which takes either a Kotlin lambda (https://github.com/scenerygraphics/scenery/blob/cc09a896b0e2f1697bbdb70aca0932a2eec33c35/src/main/kotlin/graphics/scenery/Node.kt#L561) or a `Consumer<Node>` (https://github.com/scenerygraphics/scenery/blob/cc09a896b0e2f1697bbdb70aca0932a2eec33c35/src/main/kotlin/graphics/scenery/Node.kt#L572) -- is this good enough or do you require sth else? I don't understand why the return type should be Vector4 :confused:

**Comment by kephale** [comment]
LOL

One lesson learned: don't use `node.runRecursive` with a function that adds children to the node

**Comment by kephale** [comment]
Linking to the issue from @tferr that originally suggested the idea https://github.com/scenerygraphics/sciview/issues/217
