### ISSUE TITLE
Verify that image and volume have the same orientation

### ISSUE THREAD

**Issue by kephale** [scenerygraphics/sciview#252]
Specifically check the y-axis, it looks flipped

**Comment by skalarproduktraum** [comment]
It would be possible to flip that relatively easy on the scenery side. Do you want flipping?

**Comment by xulman** [comment]
I also experienced that volume seems to be y-axis flipped... (OpenGL-ppl vs. Image-ppl favourite)

I'm actually flipping z-axis too, both y and z axis.. only then I feel the volume is displayed the same as in BDV
(I was doing `someVolume.setScale(vector_with_yElem_mult_by_minusOne)`)

**Comment by xulman** [comment]
next to it, on master commit d4f219d2b1 I cannot make the volume rotated by changing its model or world matrices, the changes are simply not saved (or I am making somewhere a terrible mistake)

**Comment by xulman** [comment]
**aspect ratio problem**: when I show anisotropic data it is displayed/rendered anisotropic... well, while it is probably also okay solution, it is again in contrast how BDV is showing such data

I'm currently considering `Source`'s `getVoxelDimension()` to read out the voxel aspect ratio and adjust the volume via its `setScale()`...:
```
		float min = voxelDims[0];
		for (int i = 1; i < voxelDims.length; ++i) min = Math.min( voxelDims[i], min );
		for (int i = 0; i < voxelDims.length; ++i) voxelDims[i] /= min;
```
this, I believe, mimics how BDV does coordinates, but don't `setScale()` work along world x,y,z axes?

What if BDV's data are somehow rotated? well, BDV knows how, it is stored in the source's transform (and that trasform combines both: the placing of the volume data + correction for anisotropy), so I was trying to push the source's transform into the volume's model matrix... but it the matrix seems to be ignoring whatever I set() into it....

**Comment by xulman** [comment]
the **apect ratio problem** can be solved:
```
v.setWantsComposeModel(false); //makes position,scale,rotation be ignored, also pxToWrld scale is ignored
final float scale = 0.5f;      //alternative to v.setPixelToWorldRatio(scale);
v.setModel( new Matrix4f(scale,0,0,0, 0,-scale,0,0, 0,0,-scale,0, 0,0,0,1) );
v.setNeedsUpdateWorld(true);
//now the volume's diagonal in world coords is now:
//      [0,0,0] -> [scale*origXSize, -scale*origYSize, -scale*origZSize]
```

the volume itself comes from BVV already after BDV transforms (which already includes the anisotropy corrections), so all good

**Comment by xulman** [comment]
> next to it, on master commit [d4f219d](https://github.com/scenerygraphics/sciview/commit/d4f219d2b1e8d58582567129b3ceef120e4889db) I cannot make the volume rotated by changing its model or world matrices, the changes are simply not saved (or I am making somewhere a terrible mistake)

please ignore this one, I never cared to understand what the `wantsComposeModel` flag is good for... now I understand why my model matrix was not updated (it was, but eventually was replaced from position,rotation and scale because of the default `wantsComposeModel = true`)

**Comment by kephale** [comment]
LGTM on testing
<img width="1276" alt="image" src="https://github.com/scenerygraphics/sciview/assets/400105/3debeead-e643-4ae4-9840-78564f829504">
