### ISSUE TITLE
Verify java 11 compatibility

### ISSUE THREAD

**Issue by kephale** [scenerygraphics/sciview#253]

**Comment by skalarproduktraum** [comment]
* [ ] check scenery Java 11 compatibility
* [ ] check sciview Java 11 compatibility

**Comment by imagejan** [comment]
It looks like the exception was fixed by @ctrueden in https://github.com/scijava/script-editor/commit/3899427ac930c534911284f7d3cf46d79371fed0, right?
Did you try with a `script-editor` version `>= 0.5.2`?

**Comment by skalarproduktraum** [comment]
Thanks a great catch, thank you, @imagejan, I'll try this right away 👍

**Comment by skalarproduktraum** [comment]
@imagejan's suggestion made the exception go away, so that problem is fixed with https://github.com/scenerygraphics/scenery/commit/37a0dd7dab3169c35397e1557c888c75fba9fdf3 👍 Thanks again!

**Comment by imagejan** [comment]
👍
it would be even better to fix this upstream with a PR to [`pom-scijava`](https://github.com/scijava/pom-scijava/blob/f10db62f9b672a594054334afe71a14b0fad7b12/pom.xml#L212-L213) (although I hope @ctrueden might be bumping versions of several components in batch very soon...) 😃

**Comment by ctrueden** [comment]
> I hope @ctrueden might be bumping versions of several components in batch very soon

1. Finish urgent writing project
2. Retire an old web server
3. Fix imagej-ops / imagej-scripting clash and release pom-scijava 28
4. Blanket update of pom-scijava component versions, melting pot test, and release pom-scijava 29
5. 🥳

Thanksgiving holiday will slow me down, but I'll keep trying!

If anyone has bandwidth to help with (3) in the meantime, the branch is `fix-imagej-scripting` on imagej-ops. But it's a tough one.
