### ISSUE TITLE
Double check version management for update site

### ISSUE THREAD

**Issue by kephale** [scenerygraphics/sciview#261]
This problem is unexpected because the fix was deployed to the update site already

https://forum.image.sc/t/sciview-requirements-for-fiji-users/36325/5

**Comment by kephale** [comment]
I'm having trouble reproducing this on Ubuntu from the current version on the update site. @skalarproduktraum could you check on Windows please?

**Comment by kephale** [comment]
We should change the upload to update site to use the git hash on the sciview jar

**Comment by kephale** [comment]
see https://travis-ci.org/github/scenerygraphics/sciview/jobs/675752625#L2128

There is a problem with deployment to the update site

**Comment by skalarproduktraum** [comment]
This was a sync issue between Fiji and pom-scijava. Fixed now, open again if it reoccurs.
