### ISSUE TITLE
obsolete Edit->Sciview Settings

### ISSUE THREAD

**Issue by xulman** [scenerygraphics/sciview#284]
![Screenshot_20200903_165943](https://user-images.githubusercontent.com/10509335/92131998-e0fb4700-ee06-11ea-94a7-01481b88992f.png)

this dialog seems ineffective, perhaps should be hidding the respective panels? do we need the dialog for hiding at all?

**Comment by kephale** [comment]
Closed by https://github.com/scenerygraphics/sciview/pull/447
