### ISSUE TITLE
Refactor vector

### ISSUE THREAD

**Issue by kephale** [scenerygraphics/sciview#290]
When doing the big kotlin refactor (https://github.com/scenerygraphics/sciview/issues/289), consider eliminating sciview vector types.

The main advantage of using internal vector types:
- ability to buffer interop issues, but scenery switched to interop-friendly data structures with joml 
- some of the default method implementations are useful, but perhaps all of these could be kotlin extension functions applied to joml types

scenery requires the use of joml types, therefore many sciview vectors get memory copied during processing methods

**Comment by kephale** [comment]
@skalarproduktraum what do you think about this? You weren't big on the Vector3 types anyway. With the way the code has progressed, I'd rather just eliminate these internal vector types.

**Comment by skalarproduktraum** [comment]
Vector types have been removed as of #304.
