### ISSUE TITLE
Inspector panel resizing works unreliably

### ISSUE THREAD

**Issue by xulman** [scenerygraphics/sciview#297]
~~when resizing the right-hand side panel, the area left for the rendering needs to change as well (of course!) which triggers current renderer to re-init itself~~

~~on my two machines, the re-init works but has limited (less than 4-6) attempts within a short period of time, in other words, when I allow it to have more re-init attempts, it bails out soon~~

dragging and resizing the panel is then a no-go for me, I need to be lighting fast (not to hold/drag it long) and give it pauses

besides, the panel resizing works funky on my KDE desktop

~~(talking about the most recent GUI of sciview, with infty floor and theoretically nicer panel)~~

EDIT @skalarproduktraum: Filtered out the relevant parts, see below.

**Comment by skalarproduktraum** [comment]
Hey @xulman! Do you have some more details on your machines (OS, GPU, etc)? I quickly tried to verify this on Win10/GTX1650 on the latest dev drivers, there the resizing works. Changing the inspector size is still a bit shaky, but I will fix that very soon.

**Comment by skalarproduktraum** [comment]
Also, does collapsing/reopening the side panel cause issues?

**Comment by xulman** [comment]
Hi @skalarproduktraum 
I APOLOGIZE, the problem was between the chair and the keyboard... not in sciview/scenery.

My both boxes are OpenSuse Linux and both update themselves somewhat in the same "waves", the recent wave brought in some graphics drivers updates and wanted me to reboot the computer afterwards... and I have forgotten to do so (in reality I refused to do now because of some WIP, you know), so it was living with old drivers running in kernel and even libs that got not unloaded were at their old version while new stuff was available and loaded on demand... 

to verify this issue, I rebooted twice :-), brought pulled sciview/scenery to their recent masters and wanted to show it off, but I didn't manage... it works even when I brought in the "big PR"...  then I blamed the code that made me write this issue and that is based on some not-so-recent scenery/sciview (and that had a copy of it aside), but works well now.. ach jo, false alarm, I'm sorry

**Comment by xulman** [comment]
collapsing/reopening works well (with dbl-clicking -- hmm, this should go into help, it didn't occur to me to dbl-click to open, was trying to "catch the edge" all the time before you told me the secret :-) )

opened panel is difficult to resize, it is hard to find a position in which  mouse cursor signals "drag to change", the drag-me zone is very narrow, this is true not only along vertical edge (scene vs. panel), also along horizontal (inside panel, e.g. between the scene tree and node inspection) -- this is not true only when it is opened for the first time (first opening, all works well, second opening, it's scrued as described, restarting sciview, first opening all good, second+ all wrong)

the REPL panel was often started showing only the "console pane", I kept forgetting about the left "hinting pane where variables are listed" because it usually was hidden... but now I cannot restore this behaviour now, aha, see below

resizing horizontally (the division between scene and the opened panel) works interestingly:
- for inspector/scene graph, on mouse drag init (so to speak) it does not allow me to move left (increase the panel size), I go right, it decreases nicely, I can go left (increases again) but not further to where the drag has started
- the above is not true for REPL, where it works as it should... aha it feels like changing while I am writing about it.... it is true for REPL too... feels like something accumulates inthere.. aha! once again:

- resizing horizontally works well only for the very first mouse-drag session, every second and on-ward is acting as described above, it does not matter if the "first session" happens to be on inspector or on REPL window

- ha, when I do the "first resizing session"on inspector, the REPL then shows "w/o" the variables list (w/ the list hidden)
- dbl-clicking to show it for the first time, dbl-click to hide it, dbl-click to show it again, and it's already on downhill track

it seems that hiding the panel "some how changes" it, in the very first show up, all works good, but only in the very first show up


-------------
sorry, didn't want to come up with substitute problem, this behaviour is there for some time (I originally even disliked that you switched to the new layout because the older one worked better) but I always though it a consequence of the vulkan working seemingly bad.. after the reboot, I see it is the panel itself...

**Comment by xulman** [comment]
with OpenGLRenderer there is no "first session", it is directly not good

**Comment by xulman** [comment]
yes

for some reason, it reacts naturally only when it is opened for the first time;

feels also a little like some busy cycles... because how else can you force OS to be very slow at at showing the right mouse cursor drawing when hovering at the right place? but didn't notice anything in atop, htop, or alike

**Comment by kephale** [comment]
Related to https://github.com/scenerygraphics/sciview/issues/311

I also can confirm this issue. I see it with OpenGLRenderer

**Comment by frauzufall** [comment]
Same issue here, also the double click as @xulman mentioned is really not intuitive, there should be a button or something (e.g. like the new BDV side panel expand button) to toggle the panel size.

**Comment by kephale** [comment]
Related to https://github.com/scenerygraphics/sciview/issues/257

**Comment by xulman** [comment]
works on my computer (linux, complicated as always :-)... but tried several times to click the two top-right icons and the panel kept rolling-in/out etc.. even window resizing works (which was not necessarily always the case previously)

from my side: you can close this one

**Comment by kephale** [comment]
awesome, thank you @xulman
