### ISSUE TITLE
Floor rendering inaccurate

### ISSUE THREAD

**Issue by kephale** [scenerygraphics/sciview#312]
See 
![image](https://user-images.githubusercontent.com/400105/100223972-785eca80-2f1c-11eb-8eb4-61e3be52e3a8.png)
and
![image](https://user-images.githubusercontent.com/400105/100223987-7d237e80-2f1c-11eb-8eaf-9f472c164b2d.png)

The only difference between these images is that the camera has rotated, but the floor+sphere intersection makes it look like the sphere has been moved w.r.t. the floor.

**Comment by kephale** [comment]
Just to point out, this is only happening in OpenGLRenderer

**Comment by skalarproduktraum** [comment]
Fixed with 7fa6ec9 👍
