### ISSUE TITLE
Overload icon

### ISSUE THREAD

**Issue by kephale** [scenerygraphics/sciview#32]
The idea is in here:

https://github.com/ClearVolume/ClearVolume/blob/master/src/java/clearvolume/utils/ClearVolumeJFrame.java

**Comment by ctrueden** [comment]
You want to override the application icon? Why?

**Comment by kephale** [comment]
We'd rather have the sciview logo than: 
![image](https://user-images.githubusercontent.com/400105/54200378-8d3ac680-44cb-11e9-88ae-e163509c6a69.png)

**Comment by kephale** [comment]
I'm closing this because we're primarily focused on being a Fiji plugin now.
