### ISSUE TITLE
Cutting releases

### ISSUE THREAD

**Issue by kephale** [scenerygraphics/sciview#322]
this hash of scijava-scripts works for cutting releases: eb4048825e47c0e757bd6fd2e294bd31b4a933df

**Comment by imagejan** [comment]
Linking here for convenience:
https://github.com/scijava/scijava-scripts/commit/eb4048825e47c0e757bd6fd2e294bd31b4a933df

**Comment by kephale** [comment]
Thanks @imagejan. I have to say I ended up quite frustrated by all of the changes in scijava scripts since our last release. They drastically changed my workflow for cutting releases (e.g. by enforcing a lot of requirements). It turned out that when I was time limited to make an I2K release, that trying to handle all of the scijava-script requirements made it impossible to cut a quick release. For that reason I wanted to at least track the last version of scijava-scripts that was used to make sure that doesn't happen again.

**Comment by imagejan** [comment]
thanks for clarifying, @kephale, that makes sense. In general, I think @ctrueden implemented the strict requirements for a good reason (e.g. make sure that you have no local untracked changes when trying the local build before proceeding, etc.), but if you think some of them are unnecessary, or in the way of quick progress, I think it's worth discussing these in an issue on `scijava-scripts`, no?

**Comment by ctrueden** [comment]
> trying to handle all of the scijava-script requirements made it impossible to cut a quick release

@kephale I am sorry you experienced frustration at the hands of `release-version.sh`. The new requirements were intended help avoid mistakes, not prevent releases. Which requirement(s) specifically made it "impossible" for you?

**Comment by kephale** [comment]
@ctrueden License headers (partially because there was code included from other people's code bases: intellij and trove) and the uncommited changes for git (which IIRC got stuck in an infinite loop where `git stash` didn't fix anything and I couldn't find any changes). I do admit I was under time pressure because this was happening hours before our I2K tutorial, so things were getting very hasty. It was also compounded by my frustration with the JDK version enforcement in maven, which Saalfeld recently helped resolve. But all of that, which really had nothing to do with actual code, I have to admit, I was blowing my lid.
