### ISSUE TITLE
Investigate shader compiler crash on M370X on macOS Mojave

### ISSUE THREAD

**Issue by skalarproduktraum** [scenerygraphics/sciview#328]
@etadobson reported a crash on macOS Mojave with a AMD M370X GPU, where the the OpenGL renderer crashes on compiling shaders. 

 This can be circumvented by forcing macOS to use the integrated Intel GPU instead of the AMD GPU, see https://nathansnelgrove.com/how-to-force-your-macbook-pro-to-use-its-discrete-graphics-card-when-its-plugged-in/

**Comment by kephale** [comment]
The OpenGLRenderer has been deprecated in scenery. Although we would need to test on this hardware, this particular issue cannot happen anymore.
