### ISSUE TITLE
Bug with instancing/particle demo

### ISSUE THREAD

**Issue by kephale** [scenerygraphics/sciview#337]
![image](https://user-images.githubusercontent.com/400105/101282861-ba6af480-37d7-11eb-859d-478906a092fc.png)
Particle demo is broken

**Comment by frauzufall** [comment]
I have probably the same issue - when commenting out the instances in the Particle Demo and just displaying the single cone node, I just see weird artefacts.

**Comment by kephale** [comment]
Hm, this was fixed after the bug was reported, but the issue wasn't closed.

If all instances are commented and it is just the master node, then there shouldn't be anything displayed.

This demo is currently working for me. Although it actually has a bug with the cone orientations.

**Comment by frauzufall** [comment]
But it says `sciView.addNode(master);` in the demo, why should it not be displayed?

Here is how the demo without the instances looks like for me (you also see how the view turns black here in between):

https://user-images.githubusercontent.com/708121/103703226-73734900-4fa7-11eb-9920-73130cfd545a.mp4

.. should I create a new issue or just stay here?

**Comment by kephale** [comment]
It does have `sciView.addNode(master)`. Off the top of my head, I don't know what variable is checked (I think this is within the `Renderer`) to see if it is an "instance master" but if the node is an instance master, then the `Node` itself is not rendered but its `instances` are rendered.

Two things to check:
- if you comment out `sciView.getFloor().setVisible(false);` then does the screen go black.
- if you comment out `master.getInstances().add(n);` then do you get the glitchy rendering?

**Comment by frauzufall** [comment]
Yes, you are absolutely right, the black screen just comes from the floor becoming invisible. So that's not an example of the black screen described in the other issue, I take that back.

Commenting out only `master.getInstances().add(n);` also creates the glitches. 

Ok, it has to do with the material - they disappear if I comment out `master.setMaterial(mat);`. 

If I understand it correctly a node is an instance master if it has instances attached to it (`val instanceMasters = sceneObjects.filter { it.instances.size > 0 }` in the `OpenGLRenderer`) so when I commented out the instances it was rendered as a normal node.

**Comment by kephale** [comment]
Ok, cool, this is getting closer. 

One other thing to try is running https://github.com/scenerygraphics/scenery/blob/master/src/test/kotlin/graphics/scenery/tests/examples/advanced/MultiBoxInstancedExample.kt which uses a different shader (but still one that supports instancing)

Next, is it using the OpenGLRenderer or the VulkanRenderer? I did just now check with both renderers and both work for me. However, it is quite possible that there are more issues with the OpenGLRenderer than with the VulkanRenderer, because it is less preferred and gets tested less frequently.

The other question would be what video card/driver are you using?

**Comment by frauzufall** [comment]
On Linux and Java 8, [sciview always uses the `OpenGlRenderer`](https://github.com/scenerygraphics/sciview/blob/master/src/main/java/sc/iview/ui/SwingMainWindow.kt#L72-L73). I switched to OpenJDK 11 (where the `VulkanRenderer` is picked by default without commenting anything out) and the glitches are gone, but the viewer freezes my system for a couple of seconds now and then when moving around, making it quite hard to interact with it at all.

I ran the `MultiBoxInstanceExample` with OpenJDK 11 and this is what it prints to the console at the beginning:
```
[main] INFO VulkanRenderer - Loaded Deferred Shading (Deferred Shading, with HDR postprocessing and FXAA)
[main] INFO VulkanDevice - Physical devices: 
[main] INFO VulkanDevice -   0: Nvidia GeForce MX150 (DiscreteGPU, driver version 450.320.128, Vulkan API 1.2.133) (selected)
[main] INFO VulkanDevice -   1: Intel Intel(R) UHD Graphics 620 (KBL GT2) (IntegratedGPU, driver version 20.0.8, Vulkan API 1.2.131) 
[main] INFO VulkanDevice -   2: Nvidia GeForce MX150 (DiscreteGPU, driver version 450.320.128, Vulkan API 1.2.133) 
[main] INFO VulkanDevice -   3: Intel Intel(R) UHD Graphics 620 (KBL GT2) (IntegratedGPU, driver version 20.0.8, Vulkan API 1.2.131) 
```
It started with 0 FPS and crashed soon after with a `SIGSEGV`.

**Comment by skalarproduktraum** [comment]
@frauzufall it is weird that both your GPUs appear twice, can you gist the output of `vulkaninfo` please? There might be something fishy there.

If MultiBoxInstancedExample crashes, does it produce a `hs_err_pid[1-9*].log` file? If yes, could you please post that?

**Comment by kephale** [comment]
@frauzufall your freezing issue sounds exactly like an issue that I've had in the past. It never fully went away, only became mostly better through driver updates. For example, I get brief freezes at launch time pretty consistently. During runtime I don't really get freezes anymore, but I would get them when essentially anything changed within the scene.

The key to making it better was upgrading to version 455.38 (in general the 455 series) driver.

However, these issues really trouble me in terms of accessibility of sciview. In the past you would just revert to OpenGLRenderer when things performed poorly on the VulkanRenderer, but as you see it now has bugs with instancing.

**Comment by frauzufall** [comment]
@kephale yes, updating to a 455 driver makes the freezes go away. So just to sum up in my case sciview needs to be executed with Java 11 and Nvidia 455. That should probably be documented somewhere.. I can look into the OpenGLRenderer if that's helpful.

**Comment by frauzufall** [comment]
@skalarproduktraum let me be more precise, it crashes when I close the script interpreter window.
[vulkaninfo.txt](https://github.com/scenerygraphics/sciview/files/5775976/vulkaninfo.txt)
[hs_err_pid16484.log](https://github.com/scenerygraphics/sciview/files/5775975/hs_err_pid16484.log)
The files were created after the driver update, here is the current output on the console:
```
[main] INFO VulkanDevice - Physical devices: 
[main] INFO VulkanDevice -   0: Nvidia GeForce MX150 (DiscreteGPU, driver version 455.180.64, Vulkan API 1.2.142) (selected)
[main] INFO VulkanDevice -   1: Intel Intel(R) UHD Graphics 620 (KBL GT2) (IntegratedGPU, driver version 20.0.8, Vulkan API 1.2.131) 
[main] INFO VulkanDevice -   2: Nvidia GeForce MX150 (DiscreteGPU, driver version 455.180.64, Vulkan API 1.2.142) 
[main] INFO VulkanDevice -   3: Intel Intel(R) UHD Graphics 620 (KBL GT2) (IntegratedGPU, driver version 20.0.8, Vulkan API 1.2.131) 
```

**Comment by skalarproduktraum** [comment]
@frauzufall maybe we can make a screen sharing session these days? I'd like to get to the bottom of this 👍

**Comment by kephale** [comment]
@skalarproduktraum bump

**Comment by kephale** [comment]
This issue has diverged a lot from the original bug report. I've confirmed that the particle demo is working currently. I'm closing this issue but we can reopen if these issues happen again.
