### ISSUE TITLE
Node selection via single click instead of double click

### ISSUE THREAD

**Issue by frauzufall** [scenerygraphics/sciview#341]
Nodes are currently selectable via double click, which is not intuitive since in pretty much all applications items are selected via single click. We discussed that there might be a technical barrier since click and drag is a separate action, but we might at least try to figure out if a single click (and release) is distinguishable and can be used for selection.

**Comment by xulman** [comment]
I often click into a scene for WASD to work... or mouse scroll (zoom-in/out)...

also selecting objects in the scene window is not very reliable... it does not work well if objects are too far, if one clicks rather way from their centre, if they are mid-far and close the side of the scene window...

this is not meant to be harsh: but sciview needs now solidify before moving forward, IMHO
