### ISSUE TITLE
Migrate SwingGroupingInputHarvester to scijava-ui-swing

### ISSUE THREAD

**Issue by imagejan** [scenerygraphics/sciview#346]
This is a reminder to *pleeease* migrate [`SwingGroupingInputHarvester`](https://github.com/scenerygraphics/sciview/blob/121e036477da69bb2706140297171105e94c1700/src/main/java/sc/iview/ui/SwingGroupingInputHarvester.kt) to `scijava-ui-swing` 😃 

See https://github.com/scijava/scijava-common/issues/310#issuecomment-733918095.

**Comment by kephale** [comment]
@ctrueden This is likely to fall off of my radar. Also, I'm unsure how we want to label this w.r.t. 1.0.0

**Comment by ctrueden** [comment]
I guess I should just finish it ASAP, huh? It seems like several people want/wanted this, and even worked on it in scijava/scijava-common#310, but no one completed the work and filed the PR upstream.

**Comment by ctrueden** [comment]
Closing in favor of scijava/scijava-ui-swing#81.

**Comment by ctrueden** [comment]
There you go, not your problem anymore @kephale!
