### ISSUE TITLE
SciJava log displays with weird texture background on Linux

### ISSUE THREAD

**Issue by frauzufall** [scenerygraphics/sciview#347]
On my Linux machine, the SciJava log displays have a texture of the viewer as a background. These screenshots are produced by clicking on `Edit > Add > Label Image` in the menu. They are responsible, just the background is weird (and if the viewer is currently black there, it is not readable at all).

![image](https://user-images.githubusercontent.com/708121/103707387-d2888c00-4fae-11eb-9546-88cf7c5c4bc7.png)
![image](https://user-images.githubusercontent.com/708121/103707439-eaf8a680-4fae-11eb-9fee-fa939c75320a.png)

**Comment by skalarproduktraum** [comment]
Does that only happen if there's a graphical glitch as well?

**Comment by frauzufall** [comment]
@skalarproduktraum yes, it happens with the OpenGLRenderer but not with the VulkanRenderer.

**Comment by kephale** [comment]
@ctrueden do you see this now?

**Comment by ctrueden** [comment]
Nope, I can't reproduce this... A lot has changed, I'm on Ubuntu 23.04, and there's only the Vulkan renderer now. I suggest we close this until such time as anyone runs into it again.

**Comment by kephale** [comment]
Awesome, thank you!
