### ISSUE TITLE
Sort file / volume / labeling import

### ISSUE THREAD

**Issue by frauzufall** [scenerygraphics/sciview#348]
Currently, `Edit > Add > Volume` and `Edit > Add > Label Image` only works if sciview is started as a plugin in Fiji with open images. `File > Open` will always import datasets as a volume. These issues needs to be fixed:
- make importing labelings and volumes work both from the standalone and from the plugin version
- sort the menu structure

We discussed maybe moving the `Add` menu without the volume and labeling import to the top menu, and then having an `File > Import` menu with a way to import a file and either autodetecting the type or specifying the node type that should be created from the file.

**Comment by kephale** [comment]
@ctrueden I'm flagging you on this one. I'm not sure if you want to dive in, but this might be faster for you.

**Comment by kephale** [comment]
Closed by https://github.com/scenerygraphics/sciview/pull/433
