### ISSUE TITLE
refresh/rebuild inspector tree (if visible) when node name changed to be longer

### ISSUE THREAD

**Issue by xulman** [scenerygraphics/sciview#354]
Hi, when I change name of a node, esp. when I make it longer, the inspector's tree keeps using the original "reserved space" for the name... which ends up in an opposite effect: less is shown from the name because dots are inserted..., e.g. orig node name "box" -> edit to "box red" -> is shown as "bo..."

**Comment by frauzufall** [comment]
This should be fixed once https://github.com/scenerygraphics/sciview/pull/344 is merged.

**Comment by xulman** [comment]
thanks @frauzufall , that will be great... looking forward
(the good-old GUI of sciview was not suffering from this :-)

**Comment by kephale** [comment]
@xulman can we close this?

**Comment by kephale** [comment]
Is this the same as https://github.com/scenerygraphics/sciview/issues/446 ?

**Comment by kephale** [comment]
Verified as closed

**Comment by kephale** [comment]
<img width="521" alt="image" src="https://github.com/scenerygraphics/sciview/assets/400105/eca6dea9-a151-4fe3-a6ba-eef983e47efa">
