### ISSUE TITLE
some controls are promised in the F1 but don't work -> ctrl does not work at all? (Linux)

### ISSUE THREAD

**Issue by xulman** [scenerygraphics/sciview#356]
- nodes dragging+ rotating (ctrl+mouseSomeAction)
- W works, shift+W works faster, ctrl+shift+W works the same as shift+W
- ctrl+rightMouse (scene rotate, as if 'R' alone) does nothing, I mean does what rightMouse does alone

(using the latest Fiji with the latest+official sciview from update site)

**Comment by xulman** [comment]
but the control itself probably work,
if I remap e.g. nodes draggin from ctrl+something to N+something... it works beautifully

**Comment by xulman** [comment]
interestingly, when I start the same revision 12709a0d from IDE, ctrl works well
(also works well in some older Fiji with some older sciview I happened to find on my harddrive)

**Comment by skalarproduktraum** [comment]
So @xulman, this is on Linux? What desktop environment are you using?

**Comment by xulman** [comment]
update on this: from IDE, with sciview's now-master (commit 5973ba5a745a) and starting the `src/main/kotlin/Main.tk` the controls are somewhat wrecked... e.g. Edit -> Settings -> Controls or Key bindings.. nothing shows up
