### ISSUE TITLE
Sciview crashes ImageJ when starting

### ISSUE THREAD

**Issue by andrewrgross** [scenerygraphics/sciview#366]
I just installed SciView. I'm using ImageJ 1.53c with Java v 1.8.0_172. When I open the SciView plugin in shows a starting screen for about a second and then the starting screen and ImageJ close abruptly. Any advice on how to troubleshoot this?

**Comment by kephale** [comment]
There is a compatibility issue between Java8 and sciview. We require Java 11. The fix for the moment is to just use Java11. 

Part of the next steps for sciview/Fiji involve upgrading Fiji to Java 11, this issue is tracking that: https://github.com/scenerygraphics/sciview/issues/520
