### ISSUE TITLE
Distance measurement tool

### ISSUE THREAD

**Issue by kephale** [scenerygraphics/sciview#37]
We need a tool for easily measuring distances in 3D

**Comment by skalarproduktraum** [comment]
How about I provide facilities for that and you use them in ThreeDViewer?

**Comment by kephale** [comment]
We need:
- [ ] a picker for object selection
- [ ] a 3D cursor tool to select points in space that are not on an object (kind of like the ray of spheres that is currently created if you double-click on empty space in 3DV, but instead only make 1 sphere that you can slide along the ray using mouse scroll). This is pretty much exists already.
- [ ] a line in 3D space between 2 points

**Comment by kephale** [comment]
All of the required scenery support now exists for this.

**Comment by kephale** [comment]
Active in https://github.com/scenerygraphics/sciview/tree/measurement

**Comment by kephale** [comment]
@Domino2357

**Comment by Domino2357** [comment]
Oh, the 3D cursor already exists! Okay, maybe my work is still valuable.

**Comment by Domino2357** [comment]
Here is the plan:
1. Click on a point on the screen and draw a line with the mouse drag (just like in paint). [x]
2. Pick two meshes and measure the distance between them, moreover, the ability to create these meshes. [ ]  (in progress)

**Comment by Domino2357** [comment]
![image](https://user-images.githubusercontent.com/45595982/98552438-c1691a80-229e-11eb-9b64-f16888c56b67.png)

**Comment by Domino2357** [comment]
@kephale or @skalarproduktraum would one of you be so kind to point me to the 3D-Cursor?

**Comment by kephale** [comment]
https://github.com/scenerygraphics/sciview/blob/master/src/main/java/sc/iview/SciView.java#L1036
its the ObjectSelection. it isn't exactly a 3D cursor though

**Comment by kephale** [comment]
https://github.com/scenerygraphics/scenery/blob/master/src/test/kotlin/graphics/scenery/tests/examples/basic/DistanceMeasurement.kt

**Comment by kephale** [comment]
@Domino2357 @skalarproduktraum Where are we on this? IIRC @Domino2357 has completed the work on the scenery side already.

**Comment by kephale** [comment]
This has been implemented https://github.com/scenerygraphics/sciview/blob/7227a02a228095beab22c8201558c1b7992adc81/src/main/kotlin/sc/iview/controls/behaviours/Ruler.kt#L46 but is not very exposed in the UI. We may want to revisit the UX of distance measurement at some point. However, I'm closing this as completed.
