### ISSUE TITLE
Migrate examples into separate repo

### ISSUE THREAD

**Issue by kephale** [scenerygraphics/sciview#372]
@frauzufall and I discussed migrating the examples out of the main sciview repo into their own. This comes with an additional suggestion that we would actually have 2 repos of examples: 1 for Java implementations, and 1 for Kotlin implementations.

This would require some changes to scripts in https://github.com/scenerygraphics/sciview-update-sites (and the corresponding scripts for releasing to the SciView-Unstable update site in the main sciview repo), where we would need to add the sciview-examples-kotlin repository to the update site.

bump to @elect86 and @skalarproduktraum for discussion.

**Comment by skalarproduktraum** [comment]
Would you still ship them together with sciview?

**Comment by kephale** [comment]
Definitely. We are going to need to eventually revamp the `SciView-Unstable` deployment, but as is the stable update site is setup on https://github.com/scenerygraphics/sciview-update-sites, which can easily add in a supplemental examples package (presumably from the proposed `sciview-examples-kotlin` repo)

**Comment by kephale** [comment]
@skalarproduktraum @ctrueden I'm revisiting this discussion after some time. This doesn't sound like a good use of our time right now, or even before 1.0.0.

**Comment by elect86** [comment]
What were the reasons in the first place?

**Comment by kephale** [comment]
I believe we wanted to make it easier for folks to work with smaller/simpler projects that changed less. Also to make it possible for a Java/Maven dev to have a project without needing to adjust to the gradle/Kotlin part of the codebase. That has been a pretty regular request from the community in the past.

This is something we can pretty easily do in the future, and I don't see a clear benefit at this point in time.

**Comment by ctrueden** [comment]
I like the simplicity of keeping the examples here in the same repository, as long as it doesn't bloat the repo size by many MB.

Tangentially: right now the repo is 135M, but only because @PowerOfNames's `simvis` branch bloats the repository hugely by committing many files to a `models` directory. That branch should never be merged as is, but rather reworked to never add large binaries in the first place.

Dumb question though: which files in this repo currently constitute "examples"? I couldn't figure it out.

**Comment by kephale** [comment]
> Dumb question though: which files in this repo currently constitute "examples"? I couldn't figure it out.

This should have been more clearly stated as the "demos." We aren't shipping much sample data within sciview, and things like the CREMI data are fetched from a remote source and cached locally.

**Comment by ctrueden** [comment]
Thanks guys. FWIW, I force-pushed the `simvis` branch to get rid of the erroneously committed models (@PowerOfNames told me that their addition was unintential), so now the repo is only is only 16MB! :tada:

**Comment by kephale** [comment]
I'm closing this. I think the way the underlying need should be addressed is by providing more examples based on https://github.com/scenerygraphics/minimal-sciview-example-project and keeping the examples we have in the main repo.
