### ISSUE TITLE
SciView: addVolume for RAI needs default behavior for voxelDimensions

### ISSUE THREAD

**Issue by kephale** [scenerygraphics/sciview#381]
The method runs when voxelDimensions is not specified, but requires a value. As a result, this leads to:

```
java.lang.ArrayIndexOutOfBoundsException: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 0
```

When called with `sciView.addVolume(myRAI)`

**Comment by skalarproduktraum** [comment]
@kephale Do you have some line numbers? The voxel dimensions should be `Vector3f(1.0f, 1.0f, 1.0f)` if not given to `addVolume`.
