### ISSUE TITLE
extract slice size from tiff files

### ISSUE THREAD

**Issue by orena1** [scenerygraphics/sciview#390]
Hi,
Great tool!
In tiff files there is sometimes also step size, it would be great if this can be extracted from the tiff, therefore not assuming that each z-step is the same as x/y steps. 

I think this is what @clearvolume is doing.

**Comment by skalarproduktraum** [comment]
Hey @orena1! Thanks for the kind words! 

You are totally right that the metadata from the TIFFs should be taken into consideration, and I thought we did that at least at some point. I'll verify and patch it back in 👍

**Comment by kephale** [comment]
I just triaged another open issue that addresses the need for missing data. It should also have the 1.0.0 label.

**Comment by kephale** [comment]
This issue is related  https://github.com/scenerygraphics/sciview/issues/420
