### ISSUE TITLE
Update site ships outdated imglib2-cache version?

### ISSUE THREAD

**Issue by tpietzsch** [scenerygraphics/sciview#402]
According to this https://github.com/imaris/imglib2-imaris-bridge/issues/1 sciview still ships imglib2-cache-1.0.0-beta-13 (?)
Could you remove that? (current Fiji has beta-16 already)

**Comment by kephale** [comment]
@ctrueden this is probably resolved now?

**Comment by ctrueden** [comment]
Yes! ☺ The sciview update site no longer shadows imglib2-cache, so the same version as core will be used (v1.0.0-beta-17 as of this writing).
