### ISSUE TITLE
Volumes may not be fully deleted

### ISSUE THREAD

**Issue by kephale** [scenerygraphics/sciview#409]
Tested by:
running in intellij, ImageJMain (on ubuntu)
ImageJ bar: open samples > T1 Head
sciview: add volume
sciview: select volume in inspector
sciview: delete volume

The inspector still has attributes open for the volume
@skalarproduktraum

**Comment by kephale** [comment]
If the object that is currently selected gets deleted, then we should reset the properties panel.

**Comment by moreApi** [comment]
#463 will resolve the describet issue but if I remember correctly sceneries volume manager currently doesnt handle deleting volumes correctly but that is not visible on the frontend.
