### ISSUE TITLE
Compatibility with 3D_Viewer

### ISSUE THREAD

**Issue by tferr** [scenerygraphics/sciview#42]
The 3D viewer in [SNT](https://github.com/fiji/Simple_Neurite_Tracer/) is getting on everybody's nerves, as it now stalls half-way through the most simple operation. Before I look into it (I will spending the next months fixing SNT), I was wondering if we should start using ThreeDViewer. Do you have any advice on this? Are there any plans to make the ThreeDViewer backward compatible with the legacy 3D_Viewer?

**Comment by kephale** [comment]
Complete backward compatibility is unlikely, primarily because the 3D_Viewer API was somewhat more oriented toward ImageJ1.x's API. 

The goal is to provide the same functionality and more, but focus on embracing the design paradigms from ImageJ2. That said, we will provide a migration guide! 

Skimming through the SNT source, I think we can help you migrate pretty easily.

**Comment by tferr** [comment]
Perfect! Great news. What about using SNT as a case example in the migration guide? How can I help?

**Comment by kephale** [comment]
Yes, SNT would be a great example for migration. I hope this isn't too much of a delay, but I will ping you in 1 month (alarm set). I will arrive at CBG shortly before that, and we'll just start diving in.

**Comment by tferr** [comment]
That will work! Just wanted to say that, as you may have noticed, SNT remains pretty much all in IJ1 land. I know I am being vague here, but if at a certain point you guys think there are some legacy IJ2/IJ1 issues I should be addressing in the interim, that would useful too.

**Comment by kephale** [comment]
@tferr just an update that we're getting a lot closer to having the visualizations ready and you have not been forgotten. ImageJ2 compatibility is in place. The main things to do before we can port SNT are cleaning up a few more bugs and updating volume rendering.

**Comment by tferr** [comment]
@kephale, Glad to hear about your success.
Just an update on my side (really sorry for the late update on my side):  SNT is also being ported (very very slowly) into the ImageJ2 world. It is just everything is much slower than I expected, because I feel there are several flaws on current implementation. As is, it looks like I won't be able to get rid of SNT's reliance of IJ1's `ImagePlus`, but I should be able to remove most IJ1 dependencies. The work will start to appear on the [scijava branch of my fork](https://github.com/tferr/Simple_Neurite_Tracer/commits/scijava).

Do you have any pointers for me? a simple example of SciView usage or some gist I can use, or should I just dive deeply into SciView myself?

**Comment by tferr** [comment]
@kephale,  just wanted to mention that SNT is now fully scijava aware! I still have two major points to tackle in the new UI, but once those are ironed out, the only thing missing would be  to start thinking about SciView integration.

**Comment by kephale** [comment]
I'm closing this one because we also have an action point at the 2023 scenery/sciview hackathon in Dresden to clean up SNT and sciview compatibility.
