### ISSUE TITLE
Adding a second volume seems to duplicate the first one

### ISSUE THREAD

**Issue by frauzufall** [scenerygraphics/sciview#422]
Starting the `VolumeRenderDemo` and adding a new volume (using the T1 head) adds a blurry (?!) version of the first volume and slows down my machine drastically.

![image](https://user-images.githubusercontent.com/708121/138690565-dcd6cec6-453e-4f46-9a38-0f620b207011.png)

**Comment by moreApi** [comment]
Not sure if it is a second volume. But there is defnitly something wrong with visibilty. I can only hide all or none of the volumes by setting all volumes to visible. As long as one volume is set to visibible all volumes are visible.

**Comment by kephale** [comment]
@moreApi that sounds different, this bug is:

Run mesh demo: see the cube volume
Add T1 head: another cube is added to the scene and there is no head.

**Comment by moreApi** [comment]
Then I cant repoduce the bug. For me the head is added but it is hidden by a very small scale and transparent transfer function. But that is expected behavior in my experience.

**Comment by kephale** [comment]
@moreApi you are very correct. I now understand why the visibility part is the main issue here.

If you delete the cube volume, then you can see the T1 head without doing anything with visibility.

**Comment by moreApi** [comment]
should be solved by https://github.com/scenerygraphics/scenery/pull/544

**Comment by kephale** [comment]
This was closed by updates for scenery 0.9.0. I tested on commit `d50e2a8e920ace13b09dd0ed9e4f02646d8dd443`

<img width="1138" alt="image" src="https://github.com/scenerygraphics/sciview/assets/400105/989d8dc7-9e26-4c87-a22b-db0da2f7fd0a">
