### ISSUE TITLE
InspectorVisible and IterpreterVisible options apprearing after launch

### ISSUE THREAD

**Issue by frauzufall** [scenerygraphics/sciview#423]
![image](https://user-images.githubusercontent.com/708121/138758257-3a727277-1146-41b0-b98d-e66ef5aca131.png)

**Comment by kephale** [comment]
Related to https://github.com/scenerygraphics/sciview/issues/284

**Comment by kephale** [comment]
Closed by https://github.com/scenerygraphics/sciview/pull/447
