### ISSUE TITLE
Visibility button triggered unexpectedly

### ISSUE THREAD

**Issue by frauzufall** [scenerygraphics/sciview#430]
Hiding an object and adjusting it directly afterwards in the properties panel, for example rotating it, triggers the visibility button again and it reappears. If you click somewhere else in between, this does not happen.

**Comment by kephale** [comment]
The cause: https://github.com/scenerygraphics/sciview/blob/89f7c93a722ccc70fb20939218558c25060b97c7/src/main/kotlin/sc/iview/commands/edit/Properties.kt#L477

**Comment by kephale** [comment]
I would also note that toggling visibility in the tree does *not* toggle the visibility checkbox.

<img width="784" alt="image" src="https://github.com/scenerygraphics/sciview/assets/400105/7678a27d-4c22-42a6-abf5-302fd55bec31">

**Comment by kephale** [comment]
I think part of the problem comes from here:

https://github.com/scenerygraphics/sciview/blob/bc00b2e09e2ea8e987758da14891108f9990a915/src/main/kotlin/sc/iview/ui/SwingNodePropertyEditor.kt#L250C2-L253

But I haven't been able to figure this out yet. Bumping @skalarproduktraum

**Comment by kephale** [comment]
This may also be related to the second point that is listed in this issue: https://github.com/scenerygraphics/sciview/issues/443

**Comment by kephale** [comment]
I'm unassigning myself for now because I got stuck when poking at this.
