### ISSUE TITLE
Menu bar independent of ImageJ

### ISSUE THREAD

**Issue by kephale** [scenerygraphics/SciView#44]
Curtis had some suggestions on how to make sure it also works within ImageJ, but first let's just get it working in standalone.

**Comment by ctrueden** [comment]
Using a different `menuRoot`, no?

**Comment by kephale** [comment]
@ctrueden thank you for the reminder/pointer!

**Comment by ctrueden** [comment]
As long as you aren't coding your own `JMenuBar` / `JMenu` / `JMenuItem`. If I see you doing that, I will feel 😿 . I really hope the `MenuService` is good enough for your needs! If not, we can discuss how to improve it.

**Comment by ctrueden** [comment]
Closed via c45fe8e2fc9e869ff324fe7fe49db52abb8b8439 and c4c0b16a85dd0d0245a452e0d593482ed141829a.

To achieve this, we ended up switching to a JavaFX container, since it gave us the ability to include additional UI elements beyond the `SceneryPanel` itself.
