### ISSUE TITLE
Meshes rotating with camera

### ISSUE THREAD

**Issue by kephale** [scenerygraphics/sciview#444]
The meshes in Show Segmentations demo seem to rotate with the camera

<img width="1271" alt="image" src="https://github.com/scenerygraphics/sciview/assets/400105/22d7552d-388d-4a6f-8150-61a375ab5ea4">

After rotating a little bit

<img width="1268" alt="image" src="https://github.com/scenerygraphics/sciview/assets/400105/4b5813f0-302c-4743-8e75-087eff71f12a">

**Comment by kephale** [comment]
IIRC, @skalarproduktraum we had this issue before

**Comment by kephale** [comment]
This one really confuses me. Why does this only happen for the meshes from Show Segmentations but not CREMI?

<img width="654" alt="image" src="https://github.com/scenerygraphics/sciview/assets/400105/bae68091-2517-42ef-9a19-f16a39343799">

<img width="778" alt="image" src="https://github.com/scenerygraphics/sciview/assets/400105/86302362-1e91-4cc5-bd28-ebe62dd0ddfa">

**Comment by skalarproduktraum** [comment]
Hah! This is a fun one! There's nothing wrong here with transformations - the objects just have the wrong vertex order, so inside is outside. And as they are round, it looks like they're turning when you're moving around. Nice huh? 😂

**Comment by skalarproduktraum** [comment]
Can be solved btw by setting `isoSurfaceMesh.material().setCullingMode(Material.CullingMode.Front);` in the demo.
