### ISSUE TITLE
No way to re-add bounding grids after deleting

### ISSUE THREAD

**Issue by kephale** [scenerygraphics/sciview#448]
When creating a volume it gets an initial bounding grid. If you delete it, there is no way in the UI to re-add the bounding grid.

To reproduce:

1. Open T1 head in ImageJ
2. In sciview: Edit > Add > Volume
3. In the inspector, select the Volume's bounding grid and delete it
4. There is no way in the UI to re-add the bounding grid.
5. If you try to use: View > Toggle Bounding grid, then there is no effect

Ran into this when testing for https://github.com/scenerygraphics/sciview/issues/243

**Comment by moreApi** [comment]
I can reproduce the issue.

**Comment by kephale** [comment]
@moreApi do you want to do it or shall I?

**Comment by moreApi** [comment]
I am currently looking into the volume visibility. Feel free to take it :)

**Comment by moreApi** [comment]
@kephale are you on it? I am free again and could tackle it.

**Comment by kephale** [comment]
Not right now, if you can grab it that would be awesome!
