### ISSUE TITLE
Improve initial naming of objects added to the scene

### ISSUE THREAD

**Issue by ctrueden** [scenerygraphics/sciview#471]
When importing a mesh from a file, say `elephant.stl`, the resultant object is named Mesh in the tree view. I contend that it would be better for it to be named `elephant.stl` or `elephant.stl [Mesh]` or `Mesh [elephant.stl]` or `Mesh: elephant.stl`. Otherwise, it becomes difficult to remember which Mesh object belongs to which object in the scene, when there are more than one. Along those lines, I contend that adding multiple boxes should name them `Box 1`, `Box 2`, etc. or something like that.

At a more nitpicky level, the case of the object names is inconsistent between box, sphere, and line: the box and sphere are small case, while the Line is upper case.

**Comment by kephale** [comment]
100% support for better names
