### ISSUE TITLE
Duplicate entries in tree view when making an existing node a child of another

### ISSUE THREAD

**Issue by kephale** [scenerygraphics/sciview#504]
To reproduce:
1. Create some shapes like spheres with `SciView.addSphere`
2. Create another `Node` to use as a parent
3. Loop over the spheres and use `parent.addChild(sphere)` on each sphere

The tree view now has duplicate entries for the spheres:
<img width="953" alt="image" src="https://github.com/scenerygraphics/sciview/assets/400105/058a6e30-3e1e-4441-9aec-e3b70cf5c168">

**Comment by xulman** [comment]
I confirm, the duplicity is actually easy to be achieved with the current API... possibly in more ways..

continuing this in PR #497

**Comment by kephale** [comment]
I believe this was completed with this PR https://github.com/scenerygraphics/sciview/issues/497
