### ISSUE TITLE
Fiji crashing after update

### ISSUE THREAD

**Issue by ashleydewitte** [scenerygraphics/sciview#528]
Hello,

I'd been successfully using SciView as a part of a plugin in Fiji until this week. I left for vacation and when I came back, I updated my Fiji and then it began crashing on launch without displaying any error message. After reinstalling Fiji, I discovered the problem only occurs when I reactivate the SciView update site. I launched Fiji through my console in debug mode and the error appears to be with "org.scijava.event.DefaultEventService".  Please see below for the full console log. 

[Error Log.txt](https://github.com/scenerygraphics/sciview/files/12098284/Error.Log.txt)

I'm working on a fully updated Macbook Pro (macOS Ventura version 13.4.1 (c)). 

I've also posted this on image.sc in case I'm incorrect and this isn't an issue you can help me with (https://forum.image.sc/t/fiji-crashing-after-update/83931).

I'd really appreciate any guidance you can provide.

Thank you in advance!

**Comment by ctrueden** [comment]
I finally got around to fixing the sciview update site to ship the latest version of sciview from its main branch.

For those who we were stuck unable to use sciview in recent months: try updating again and see how it goes now.

Warning: sciview currently has some serious bugs, but it should be usable on many systems, *as long as you use Java 11, not Java 8*.
