### ISSUE TITLE
sciview often hangs on startup from Main.kt

### ISSUE THREAD

**Issue by ctrueden** [scenerygraphics/sciview#536]
On my Ubuntu Linux 23.04 machine, I'm seeing that intermittently (a high percentage of the time, unfortunately), when launching sciview from Main.kt, it hangs on startup. The main window appears, the scene canvas with grid appears, but the menu bar and sidebars may or may not ever appear. Checking the stack trace with `jstack $(ps aux | grep sciview | head -n 1 | cut -f 6 -d ' ')`, the culprit is likely this:
```
"main" #1 prio=5 os_prio=0 cpu=1635.31ms elapsed=210.82s tid=0x00007f0f6c021800 nid=0x7cc4 in Object.wait()  [0x00007f0f725fe000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(java.base@11.0.19/Native Method)
	- waiting on <0x000000062344e528> (a java.awt.EventQueue$1AWTInvocationLock)
	at java.lang.Object.wait(java.base@11.0.19/Object.java:328)
	at java.awt.EventQueue.invokeAndWait(java.desktop@11.0.19/EventQueue.java:1361)
	- waiting to re-lock in wait() <0x000000062344e528> (a java.awt.EventQueue$1AWTInvocationLock)
	at java.awt.EventQueue.invokeAndWait(java.desktop@11.0.19/EventQueue.java:1342)
	at org.scijava.thread.DefaultThreadService.invoke(DefaultThreadService.java:118)
	at org.scijava.event.DefaultEventBus.publishNow(DefaultEventBus.java:154)
	at org.scijava.event.DefaultEventBus.publishNow(DefaultEventBus.java:72)
	at org.scijava.event.DefaultEventService.publish(DefaultEventService.java:101)
	at org.scijava.display.DefaultDisplayService.createDisplay(DefaultDisplayService.java:213)
	at org.scijava.display.DefaultDisplayService.createDisplay(DefaultDisplayService.java:205)
	at sc.iview.DefaultSciViewService.makeSciView(DefaultSciViewService.java:131)
	at sc.iview.DefaultSciViewService.getOrCreateActiveSciView(DefaultSciViewService.java:175)
	at sc.iview.SciView$Companion.create(SciView.kt:1892)
	at sc.iview.Main.main(Main.kt:40)
```

I.e. a hang in scijava-common's event / thread handling, when the sciview SciJava display is first created. In order to quit the program, I have to `kill -9` the process.

This is probably not sciview's fault, rather a bug in scijava-common, but I'm filing the issue here since it negatively impacts sciview specifically.

**Comment by ctrueden** [comment]
This also happens when sciview is installed into a Fiji.app and launched as a plugin.

But I found a workaround!

Set the `XMODIFIERS` environment variable to an empty value. (Discovered from [this issue](https://youtrack.jetbrains.com/issue/IDEA-120300/UI-Hang-in-createXICNative), , where IntelliJ IDEA has the same hang)

**Comment by ctrueden** [comment]
I tried putting the following code at the beginning of `Main.kt`'s `main` function:
```kotlin
        if (com.sun.jna.Platform.isLinux()) {
            println(com.sun.jna.platform.unix.LibC.INSTANCE.setenv("XMODIFIERS", "", 1))
            println(System.getenv("XMODIFIERS"))
        }
```
But unfortunately, it does not fix the hangs. I think it must be too late—whatever is reading the `XMODIFIERS` variable must already have acted by this point? I will also try setting it in the ImageJ Launcher, and if that works, we could make the ImageJ Launcher always do this... but first I'm going to see if I can actually address the hangs on the scijava-common event subsystem side, since that appears to be where the deadlocks are happening.

**Comment by kephale** [comment]
I'm at this point on my Linux machine now. `XMODIFIERS` has me up and running on this branch https://github.com/scenerygraphics/sciview/tree/switch-to-java-21

**Comment by kephale** [comment]
I can consistently get sciview working on my Ubuntu machine when running with 

`XMODIFIERS="" ./gradlew runImageJMain`

However, the renderer does not show up in the window at launch, but does show up once you interact with the window. When running from gradlew I'm not getting crashes, but I sometimes get crashes when I run from IntelliJ.

**Comment by ctrueden** [comment]
Does it still hang if run in Fiji launched via Fiji's usual launcher? I'm wondering if this is actually the same issue that the ImageJ Launcher's XInitThreads logic intends to solve...

**Comment by ctrueden** [comment]
I think f91f457fb512ffa52e726c2f6a259b5f4e342ab5 might have fixed this bug. @kephale Can you still reproduce it?

**Comment by kephale** [comment]
It looks like it is working on my linux machine now as well!
