### ISSUE TITLE
Follow up on Controls improvements

### ISSUE THREAD

**Issue by kephale** [scenerygraphics/sciview#541]
Multiple issues arose when reviewing https://github.com/scenerygraphics/sciview/pull/532, and some require more though to address, including:

- Initial camera position does not match initial mouse drag
- Arcball mode resets camera after FPS mode camera movement

Most extensive description in https://github.com/scenerygraphics/sciview/pull/532#pullrequestreview-1542062507

**Comment by ctrueden** [comment]
Followup to9 the arcball camera reset issue: when using FPS mode with shift or ctrl + drag, it moves the camera in/out and left/right.... but there is no way (that I could find) to turn and look left or right, making it less useful to fly around FPS style than it would otherwise be.

**Comment by smlpt** [comment]
Just came across the thread in #532 and wanted to add my two cents to the point "Arcball mode resets camera after FPS mode camera movement":

This might be scenery-related behavior and might have to be changed there?
As @ctrueden already mentioned, most if not all 3D viewers also change the rotational center when panning the view. The question is, how far from the camera should the rotational center be? Assume you have a really big object in your scene, so you have to zoom out to see it well. If the rotational center had a fixed distance from the camera, you might end up rotating around too close to the camera.
I know from Blender that the zooming operation works non-linearly, meaning the zoom steps get larger the more you zoom out and smaller the more you zoom in. So maybe the distance between rotational center and camera could also be proportional to the current zoom state?

**Comment by kephale** [comment]
@xulman describes his thoughts here: https://imagesc.zulipchat.com/#narrow/stream/327495-scenery.2Bsciview/topic/arcball.20jumping
