### ISSUE TITLE
Trying to export a STL file throws a NullPointerException

### ISSUE THREAD

**Issue by rimadoma** [scenerygraphics/SciView#57]
No matter how you create a view with a mesh (add your own programmatically, run _SciView>Add Box_...), trying to export an STL file causes a _NullPointerException_ at _https://github.com/scenerygraphics/SciView/blob/master/src/main/java/sc/iview/io/ExportSTL.java#L30_ because there are no viewers in _DefaultSciViewService_.

**Steps to reproduce**
1. Run ImageJ
2. Run _SciView >Add>Box_
3. Run _SciView>Export>STL__

**Environment**
- Win 8.1 64-bit
- JRE 1.8.0_152
- Vulkan renderer (JVM -Dscenery.Renderer=VulkanRenderer)
- Lenovo G50-70

**Comment by rimadoma** [comment]
I also get a _NullPointerException_ at https://github.com/scenerygraphics/SciView/blob/master/src/main/java/sc/iview/viewing/RotateView.java#L20 when running _SciView>View>Rotate_, because there are no viewers. NPEs from anything else in the _View_-submenu. This is probably related to the same bug. Let me know if you want me to create separate issues.

**Comment by kephale** [comment]
I believe this is resolved now.
