### ISSUE TITLE
generateUniqueName is called twice in the open() member function

### ISSUE THREAD

**Issue by smlpt** [scenerygraphics/sciview#572]
Nothing big, but I noticed that [here](https://github.com/scenerygraphics/sciview/blob/813a8e6c5cbc54c4f58270bec0fb6bd68689750c/src/main/kotlin/sc/iview/SciView.kt#L752) and in a few other places `generateUniqueName()` is called before passing the node to `addNode()`, which in turns also calls `generateUniqueName()` again.

**Comment by kephale** [comment]
@smlpt i see the code you are pointing at but did you confirm that `generateUniqueName()` is actually repeatedly called? I did some quick checks with different node types that do call `generateUniqueName` before going on to call `addNode`. I didnt verify with a bdv xml though because i dont have one readily accessible.

**Comment by smlpt** [comment]
@kephale so when I add an info log to `generateUniqueName` and add a box to the scene, it logs:
```
[INFO] generated unique name Box
[INFO] generated unique name Box
```

When I open an XML-based volume, it also logs:
```
[INFO] generated unique name C:\Software\datasets\MastodonTutorialDataset1\datasethdf5.xml
[INFO] generated unique name C:\Software\datasets\MastodonTutorialDataset1\datasethdf5.xml
```

And since most other primitives and file opening operations also call `generateUniqueName` before calling `addNode`, I suspect they all call the function twice.
I guess it won't make a difference, but it is probably not the intended behavior.

**Comment by kephale** [comment]
Upps, lol. Yes, when I saw this issue i thought "that should be a quick fix" so i made the fix, then tried to replicate the bug :P
