### ISSUE TITLE
Adding a group to a Volume and then removing the group doesn't update the object inspector.

### ISSUE THREAD

**Issue by odinsbane** [scenerygraphics/sciview#578]
I've created a command in that command I 'Mesh's to a group that I add to a volume. Since there are a lot of them, I made a way to remove them from the volume. When I remove the meshes, they remain in the inspect. If I remove one of them from the inspector, it updates and the volume no longer has the groups as children.

The command lives here:

    https://github.com/Living-Technologies/SciviewDM3D 

The relevant code from [MeshVolumeDemo](https://github.com/Living-Technologies/SciviewDM3D/blob/master/src/main/java/org/livingtech/scbridge/MeshVolumeDemo.java) first adds a bunch of groups to the volume.

            Node active = sciView.getActiveNode();
            Volume v = (Volume)active;
            Group g = new Group();
            g.addChild(mesh);
            sciView.addNode(g, v);

Then in the [MeshVolumeNavigator](https://github.com/Living-Technologies/SciviewDM3D/blob/master/src/main/java/org/livingtech/scbridge/MeshVolumeNavigator.java) the groups are removed from the volume.

        TreeMap<Integer, Group> meshes;
        meshes.values().forEach(v::removeChild);

Maybe I should be removing the nodes through the sciView interface. I'm sure there are a lot of problems going on here.

**Comment by kephale** [comment]
Yes, you are correct. To get UI updates you need to use the sciview API to remove them. You would use `SciView.deleteNode`.

**Comment by odinsbane** [comment]
That works, it is slow if I don't control the publish option.

            Iterator<Group> iter = meshes.values().iterator();
            while(iter.hasNext()){
                Node node = iter.next();
                boolean publish = ! iter.hasNext();
                sciView.deleteNode(node, publish);
            }

Is there a publish method?

**Comment by kephale** [comment]
Highlighting some of the issue:

- Publishing events about nodes triggers [scene rebuilds](https://github.com/scenerygraphics/sciview/blob/5dddc25c68bcb1ded2b906df31ec8d9468a2aea6/src/main/kotlin/sc/iview/SciView.kt#L1032) and [rebuilds of the inspector tree and properties panel](https://github.com/scenerygraphics/sciview/blob/5dddc25c68bcb1ded2b906df31ec8d9468a2aea6/src/main/kotlin/sc/iview/ui/SwingNodePropertyEditor.kt#L149). 
- [SciView.deleteNode](https://github.com/scenerygraphics/sciview/blob/5dddc25c68bcb1ded2b906df31ec8d9468a2aea6/src/main/kotlin/sc/iview/SciView.kt#L1204) does take care of a few other things, but triggers a `NodeRemovedEvent` for each call.
- Some of the work triggered by `NodeRemovedEvent` shouldn't be done per-node, but instead should be per-scene/per-frame

@skalarproduktraum @ctrueden We've seen issues like this before and with enough regularity that we should probably do something more serious than the `activePublish` flag. My immediate proposal:

At both of the previously mentioned locations where `NodeRemovedEvent`s trigger updates:
- change the rebuild/update calls to flag setting logic (e.g. `Properties.isValid`)
- then run the corresponding logic in the `SciView` and `Properties` classes conditionally on a per-frame basis (e.g. each timestep check if we need to run the rebuilds)

**Comment by kephale** [comment]
@odinsbane would you consider this closed if we get this merged: https://github.com/scenerygraphics/sciview/pull/594

Otherwise having deletion work with the `removeChild` methods would be a bigger ask since that means connecting the scenery methods to the corresponding sciview instance.

**Comment by odinsbane** [comment]
Yes! I am not sure where this flag is, but when you told me to use sciview
to remove the node. That flag works ok too.

**Comment by kephale** [comment]
Great, and the PR should speed up node deletion for many nodes.
