### ISSUE TITLE
Only upload releases to ij update site

### ISSUE THREAD

**Issue by kephale** [scenerygraphics/SciView#65]

**Comment by ctrueden** [comment]
Let's discuss at the hackathon. There are several things important to note before making a decision about how this should work:

* Do you always want to upload to the update site immediately following each Maven release? What if the new version breaks components downstream?
* Do you want to use `release-version.sh` to cut new releases? (I vote yes.) If so, Travis does the release, and we could teach it to also upload at that time. But we might want to change the Travis build to use the "SciJava standard" way with `.travis/build.sh` that curls the central build script. And add extension hooks to that script. And/or make that script smart enough to do an upload as well in cases where that is desired.

**Comment by kephale** [comment]
We added support for the special commit message "Trigger update site upload" which triggers an upload to the SciView update site.
