### ISSUE TITLE
Enable bounding box display for selected objects

### ISSUE THREAD

**Issue by kephale** [scenerygraphics/SciView#74]
Scenery support via https://github.com/scenerygraphics/scenery/blob/master/src/main/kotlin/graphics/scenery/BoundingGrid.kt

**Comment by skalarproduktraum** [comment]
You can use this as (Kotlin)
```
val bg = new BoundingGrid()
bg.node = myNodeThatShouldHaveAGrid
```

**Comment by kephale** [comment]
These old ones are essentially equivalent, so I am closing them and leaving this open.

https://github.com/scenerygraphics/SciView/issues/10
https://github.com/scenerygraphics/SciView/issues/9

**Comment by kephale** [comment]
@skalarproduktraum BTW, how do you remove a BoundingGrid after creating one? removeNode from scene doesnt work.

**Comment by kephale** [comment]
@wrongapocalypse relevant branch https://github.com/scenerygraphics/SciView/tree/bounding-grid

**Comment by kephale** [comment]
and note this issue https://github.com/scenerygraphics/scenery/issues/184

**Comment by kephale** [comment]
done
