### ISSUE TITLE
SciView update site wants to downgrade imglib2-* in my Fiji

### ISSUE THREAD

**Issue by xulman** [scenerygraphics/SciView#82]
Hi,

running update Fiji today I spotted that SciView update site was attempting to downgrade some imglib2 stuff... only caught my attention because I would expect imglib2/coreFiji update site to update the imglib2 stuff. See attached screen shot:

<img width="1111" alt="screen shot 2018-06-05 at 12 18 12" src="https://user-images.githubusercontent.com/10509335/40970942-5cead22c-68bc-11e8-8d6b-e9a45517e92c.png">

Isn't there an issue that SciView is coping more by mistake?

Vlado

PS: Thanks for SciView!

**Comment by xulman** [comment]
I just have noticed that similar behavior happens with many Update sites... it's probably just how it is in this world.... so take it easy, maybe :)

**Comment by ctrueden** [comment]
@xulman Thanks for the report. It's true that quite a few update sites have this problem, but it _is_ a problem. The update sites should, in an ideal world, not shadow core libraries. I am tempted to disallow this in the future, although it is convenient in some cases.

For now, I obsoleted the shadowed core libraries on the SciView site, so everything should be back in sync for now; please reopen if not.
