### ISSUE TITLE
GoL3D as an animation

### ISSUE THREAD

**Issue by kephale** [scenerygraphics/sciview#87]
What about treating the iteration of the GoL demo as an animation?

**Comment by ctrueden** [comment]
I originally coded it as an animation (see https://github.com/ctrueden/game-of-life), but the volume update was slow enough that I decided to make iteration a button instead. But if you want to switch it back to an animation, then go for it. Gotta be careful about the threading, though—when the window closes, the animation thread needs to die.

**Comment by kephale** [comment]
:D Awesome!

That animation thread issue has to be solved for all other animations anyway!
