### ISSUE TITLE
NVIDIA Error

### ISSUE THREAD

**Issue by wrongapocalypse** [scenerygraphics/sciview#93]
[SciJava-4a57380-Thread-1] INFO SciView - Started application as PID 9292
[SciJava-4a57380-Thread-1] INFO VulkanRenderer - Loaded Deferred Shading (Deferred Shading, with HDR postprocessing and FXAA)
[SciJava-4a57380-Thread-1] INFO VulkanDevice - Physical devices: 
[SciJava-4a57380-Thread-1] INFO VulkanDevice -   0: Nvidia GeForce GTX 1050 Ti (DiscreteGPU, driver version 398.44.0, Vulkan API 1.1.70) (selected)
[SciJava-4a57380-Thread-1] INFO VulkanRenderer - Using JavaFX-based swapchain
[SciJava-4a57380-Thread-1] WARN JavaFXMouseAndKeyHandler - Could not initialize JInput: C:\Users\Nathan%20Hurlocker\.m2\repository\net\java\jinput\jinput-platform\2.0.7\jinput-platform-2.0.7-natives-windows.jar (The system cannot find the path specified)
[SciJava-4a57380-Thread-1] INFO InputHandler - No custom key configuration found, using default keybindings.
[SciJava-4a57380-Thread-1] INFO InputHandler - No custom key configuration found, using default keybindings.
[WARNING] SciView help:

0.25

[SciJava-4a57380-Thread-1] INFO VulkanRenderer - Recreating Swapchain at frame 0
[SciJava-4a57380-Thread-1] INFO FXSwapchain - Created 2 swapchain images
[SciJava-4a57380-Thread-1] INFO VulkanRenderer - Creating render framebuffer GeometryBuffer for pass Scene
[SciJava-4a57380-Thread-1] INFO VulkanRenderer -  + attachment NormalsMaterial, RGBA_Float16
[SciJava-4a57380-Thread-1] INFO VulkanRenderer -  + attachment DiffuseAlbedo, RGBA_UInt8
[SciJava-4a57380-Thread-1] INFO VulkanRenderer -  + attachment ZBuffer, Depth32
[SciJava-4a57380-Thread-1] INFO VulkanRenderer - Creating render framebuffer DSSDOTemp1 for pass DSSDO
[SciJava-4a57380-Thread-1] INFO VulkanRenderer -  + attachment Occlusion, RGBA_UInt8
[SciJava-4a57380-Thread-1] INFO VulkanRenderer - Creating render framebuffer DSSDOTemp2 for pass DSSDOBlurV
[SciJava-4a57380-Thread-1] INFO VulkanRenderer -  + attachment Occlusion, RGBA_UInt8
[SciJava-4a57380-Thread-1] INFO VulkanRenderer - Creating render framebuffer DSSDOBuffer for pass DSSDOBlurH
[SciJava-4a57380-Thread-1] INFO VulkanRenderer -  + attachment Occlusion, RGBA_UInt8
[SciJava-4a57380-Thread-1] INFO VulkanRenderer - Creating render framebuffer ForwardBuffer for pass DeferredLighting
[SciJava-4a57380-Thread-1] INFO VulkanRenderer -  + attachment Color, RGBA_Float32
[SciJava-4a57380-Thread-1] INFO VulkanRenderer - Creating render framebuffer HDRBuffer for pass ForwardShading
[SciJava-4a57380-Thread-1] INFO VulkanRenderer -  + attachment Color, RGBA_Float32
[SciJava-4a57380-Thread-1] INFO VulkanRenderer -  + attachment Depth, Depth32
[SciJava-4a57380-Thread-1] INFO VulkanRenderer - Creating render framebuffer FXAABuffer for pass HDR
[SciJava-4a57380-Thread-1] INFO VulkanRenderer -  + attachment Color, RGBA_UInt8
[SciJava-4a57380-Thread-1] WARN VulkanShaderModule - Shader path shaders/DSSDO.frag.spv not found within given classes, falling back to default.
[SciJava-4a57380-Thread-1] INFO VulkanShaderModule - Compiling shaders/DSSDO.frag to SPIR-V...
[SciJava-4a57380-Thread-1] WARN VulkanShaderModule - Shader path shaders/DeferredLighting.frag.spv not found within given classes, falling back to default.
[SciJava-4a57380-Thread-1] INFO VulkanShaderModule - Compiling shaders/DeferredLighting.frag to SPIR-V...
[SciJava-4a57380-Thread-1] INFO VulkanRenderer - Scene initialization started.
[SciJava-4a57380-Thread-1] INFO VulkanShaderModule - Compiling shaders/DeferredLighting.frag to SPIR-V...
[SciJava-4a57380-Thread-1] INFO VulkanRenderer - Scene initialization complete.
[SciJava-4a57380-Thread-1] INFO VulkanShaderModule - Compiling shaders/DeferredLighting.frag to SPIR-V...
Outstanding resource locks detected:
D3D Vram Pool: 15,790,592 used (2.9%), 67,108,864 target (12.5%), 536,870,912 max
7 total resources being managed
average resource age is 0.3 frames
0 resources at maximum supported age (0.0%)
5 resources marked permanent (71.4%)
1 resources have had mismatched locks (14.3%)
1 resources locked (14.3%)
6 resources contain interesting data (85.7%)
0 resources disappeared (0.0%)

[WARNING] SciView help:

3.5

[WARNING] SciView help:

0.3

[Timer-0] ERROR NvidiaGPUStats - Failed to get GPU usage for 0 (-220)
[Timer-0] ERROR NvidiaGPUStats - Failed to get GPU usage for 0 (-220)
[Timer-0] ERROR NvidiaGPUStats - Failed to get GPU usage for 0 (-220)
[Timer-0] ERROR NvidiaGPUStats - Failed to get GPU usage for 0 (-220)
[Timer-0] ERROR NvidiaGPUStats - Failed to get GPU usage for 0 (-220)
[Timer-0] ERROR NvidiaGPUStats - Failed to get GPU usage for 0 (-220)
[Timer-0] ERROR NvidiaGPUStats - Failed to get GPU usage for 0 (-220)
[Timer-0] ERROR NvidiaGPUStats - Failed to get GPU usage for 0 (-220)
[Timer-0] ERROR NvidiaGPUStats - Failed to get GPU usage for 0 (-220)
[Timer-0] ERROR NvidiaGPUStats - Failed to get GPU usage for 0 (-220)
[Timer-0] ERROR NvidiaGPUStats - Failed to get GPU usage for 0 (-220)
[Timer-0] ERROR NvidiaGPUStats - Failed to get GPU usage for 0 (-220)
[Timer-0] ERROR NvidiaGPUStats - Failed to get GPU usage for 0 (-220)
[Timer-0] ERROR NvidiaGPUStats - Failed to get GPU usage for 0 (-220)
[Timer-0] ERROR NvidiaGPUStats - Failed to get GPU usage for 0 (-220)
[Timer-0] ERROR NvidiaGPUStats - Failed to get GPU usage for 0 (-220)
[Timer-0] ERROR NvidiaGPUStats - Failed to get GPU usage for 0 (-220)
[Timer-0] ERROR NvidiaGPUStats - Failed to get GPU usage for 0 (-220)
[Timer-0] ERROR NvidiaGPUStats - Failed to get GPU usage for 0 (-220)
[Timer-0] ERROR NvidiaGPUStats - Failed to get GPU usage for 0 (-220)
[Timer-0] ERROR NvidiaGPUStats - Failed to get GPU usage for 0 (-220)
[Timer-0] ERROR NvidiaGPUStats - Failed to get GPU usage for 0 (-220)
[Timer-0] ERROR NvidiaGPUStats - Failed to get GPU usage for 0 (-220)
[Timer-0] ERROR NvidiaGPUStats - Failed to get GPU usage for 0 (-220)
[Timer-0] ERROR NvidiaGPUStats - Failed to get GPU usage for 0 (-220)
[Timer-0] ERROR NvidiaGPUStats - Failed to get GPU usage for 0 (-220)
[Timer-0] ERROR NvidiaGPUStats - Failed to get GPU usage for 0 (-220)
[Timer-0] ERROR NvidiaGPUStats - Failed to get GPU usage for 0 (-220)
[Timer-0] ERROR NvidiaGPUStats - Failed to get GPU usage for 0 (-220)
[Timer-0] ERROR NvidiaGPUStats - Failed to get GPU usage for 0 (-220)
[Timer-0] ERROR NvidiaGPUStats - Failed to get GPU usage for 0 (-220)
[Timer-0] ERROR NvidiaGPUStats - Failed to get GPU usage for 0 (-220)
[Timer-0] ERROR NvidiaGPUStats - Failed to get GPU usage for 0 (-220)
[Timer-0] ERROR NvidiaGPUStats - Failed to get GPU usage for 0 (-220)
[Timer-0] ERROR NvidiaGPUStats - Failed to get GPU usage for 0 (-220)
[Timer-0] ERROR NvidiaGPUStats - Failed to get GPU usage for 0 (-220)
[Timer-0] ERROR NvidiaGPUStats - Failed to get GPU usage for 0 (-220)
[Timer-0] ERROR NvidiaGPUStats - Failed to get GPU usage for 0 (-220)
[Timer-0] ERROR NvidiaGPUStats - Failed to get GPU usage for 0 (-220)
[Timer-0] ERROR NvidiaGPUStats - Failed to get GPU usage for 0 (-220)
[Timer-0] ERROR NvidiaGPUStats - Failed to get GPU usage for 0 (-220)
[Timer-0] ERROR NvidiaGPUStats - Failed to get GPU usage for 0 (-220)
[Timer-0] ERROR NvidiaGPUStats - Failed to get GPU usage for 0 (-220)
[Timer-0] ERROR NvidiaGPUStats - Failed to get GPU usage for 0 (-220)
[Timer-0] ERROR NvidiaGPUStats - Failed to get GPU usage for 0 (-220)
[Timer-0] ERROR NvidiaGPUStats - Failed to get GPU usage for 0 (-220)
[Timer-0] ERROR NvidiaGPUStats - Failed to get GPU usage for 0 (-220)
[Timer-0] ERROR NvidiaGPUStats - Failed to get GPU usage for 0 (-220)
[Timer-0] ERROR NvidiaGPUStats - Failed to get GPU usage for 0 (-220)
[Timer-0] ERROR NvidiaGPUStats - Failed to get GPU usage for 0 (-220)
[Timer-0] ERROR NvidiaGPUStats - Failed to get GPU usage for 0 (-220)
[Timer-0] ERROR NvidiaGPUStats - Failed to get GPU usage for 0 (-220)
[Timer-0] ERROR NvidiaGPUStats - Failed to get GPU usage for 0 (-220)
[Timer-0] ERROR NvidiaGPUStats - Failed to get GPU usage for 0 (-220)
[Timer-0] ERROR NvidiaGPUStats - Failed to get GPU usage for 0 (-220)
[Timer-0] ERROR NvidiaGPUStats - Failed to get GPU usage for 0 (-220)
[Timer-0] ERROR NvidiaGPUStats - Failed to get GPU usage for 0 (-220)
[Timer-0] ERROR NvidiaGPUStats - Failed to get GPU usage for 0 (-220)
[Timer-0] ERROR NvidiaGPUStats - Failed to get GPU usage for 0 (-220)
[Timer-0] ERROR NvidiaGPUStats - Failed to get GPU usage for 0 (-220)
[Timer-0] ERROR NvidiaGPUStats - Failed to get GPU usage for 0 (-220)

**Comment by skalarproduktraum** [comment]
Hey @wrongapocalypse,

so first this error has nothing to do with Vulkan, but with the NvidiaGPUStats module. The funky thing here however is that the return code -220 is not even documented by Nvidia (see https://docs.nvidia.com/gameworks/content/gameworkslibrary/coresdk/nvapi/nvapi__lite__common_8h.html). Does this happen every time or only under certain conditions?

**Comment by skalarproduktraum** [comment]
*poke*

**Comment by wrongapocalypse** [comment]
Not especially. If there is an issue with performance I haven't noticed it.

**Comment by skalarproduktraum** [comment]
Okay, thanks. Until I know more about what this particular error means, I would just disable collecting further statistics once it occurs.
